### PR TITLE
feat: `mousedown` effects

### PR DESCRIPTION
**Pull request by OverflowCat**
Enhance cursor feedback by adding scaling and transparency changes when `mousedown` and `mouseup` events are fired.

### CODE REVIEW

**Comment by CatsJuice** [comment]
@OverflowCat  Thx, that's what I've always wanted to do.

However this is one thing that I can't understand, is it necessary to define mouse `down` and `up` for `normal` | `text` | `block`?

In my opinion it will be much more complex and may be confusing for these state, such as what difference between `normalStyle` and `normalUpStyle`? It may be confusing for me to chose which to use when I just want to customize basic style.

Maybe for most use cases, an extra `mouseDownStyle` is enough?

**Comment by OverflowCat** [comment]
The `normalUpStyle` is used to revert the style that takes effect during mouse down (`normalDownStyle`), while `normalStyle` is aimed at overriding other styles when the cursor is switching between normal/text/block. If we remove `UpStyle`s and use full style rollback, block/text styles might fail to apply in some cases. In such situations, given that the color transparency is different for normal/text/block, it is necessary to maintain three different up/down styles.

Granted, it is indeed confusing though. If we use one single `downStyle`, my suggestion is to take the intersection of the properties of `normal`/`text`/`blockStyle` & those of `downStyle` to derive corresponding `upStyle`s. Also I believe it would make life easier to refactor the `updateCursorStyle` function by utilizing separate classes with distinct properties instead of injecting inline CSS.

**Comment by CatsJuice** [comment]
> properties

I tried to use only one `mousedown` state base on your changes in branch [mousedown-effect](https://github.com/CatsJuice/ipad-cursor/tree/feat/mousedown-effect)

The second problem you discovered still exits.

**Comment by CatsJuice** [comment]
And I think that, it's strange to add `mousedown` scale effect for `block` if the target not not scaled together.

**Comment by CatsJuice** [comment]
I've changed the logic of recover style when mouse-up in this [commit](https://github.com/CatsJuice/ipad-cursor/commit/e59726b4ca04f09127082688f22a666fc75c9f6e). It should work with element's custom style by `data-cursor-style`.

**Pull request merged**
